version: "3.8"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  traced-app-1:
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_OTEL_SDK_DISABLED=false
      - QUARKUS_OTEL_RESOURCE_ATTRIBUTES=service.name=App1
      - EXTERNAL_SERVICE_URI=http://traced-app-2:8080
      - TRACING_SERVER_URI=http://jaeger-all-in-one:4317
  traced-app-2:
    build:
      context: ./
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_OTEL_SDK_DISABLED=false
      - QUARKUS_OTEL_RESOURCE_ATTRIBUTES=service.name=App2
      - EXTERNAL_SERVICE_URI=http://traced-app-1:8080
      - TRACING_SERVER_URI=http://jaeger-all-in-one:4317