services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    ports:
      - "4317:4317"
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://elasticsearch:9200/_cluster/health >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.60
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "4318:4318"   # OTLP HTTP receiver
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
  jaeger-query:
    image: jaegertracing/jaeger-query:1.60
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "16686:16686" # Jaeger UI
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
  traced-app-1:
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_OTEL_SDK_DISABLED=false
      - QUARKUS_OTEL_RESOURCE_ATTRIBUTES=service.name=App1
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - EXTERNAL_SERVICE_URI=http://traced-app-2:8080
  traced-app-2:
    build:
      context: ./
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_OTEL_SDK_DISABLED=false
      - QUARKUS_OTEL_RESOURCE_ATTRIBUTES=service.name=App2
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - EXTERNAL_SERVICE_URI=http://traced-app-1:8080
